Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_view
from django.conf.urls.static import static
from django.conf import settings
from django.urls import re_path
from django.views.static import serve


urlpatterns = [
    path('adminlogin/', admin.site.urls),
    path('', home_view, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.register_view, name='register-view'),
    path('login/', views.login_view, name='login-view'),
    path('logout/', views.logout_view, name='logout-view'),
    path('activate/<uidb64>/<token>/', views.activate_view, name='activate-view'),
    path('dashboard/', views.dashboard_view, name='dashboard-view'),
    path('', views.dashboard_view, name='dashboard-view'),
    path('forgot_password/', views.forgot_password_view, name='forgot-password-view'),
    path('resetpassword/<uidb64>/<token>/', views.password_validate_view, name='password-validate-view'),
    path('reset_password/', views.reset_password_view, name='reset-password-view'),
    path('my_orders/', views.my_orders_view, name='my-orders-view'),
    path('edit_profile/', views.edit_profile_view, name='edit-profile-view'),
    path('change_password/', views.change_password_view, name='change-password-view'),
    path('order_detail/<int:order_id>/', views.order_detail_view, name='order-detail-view'),

    ]

carts/urls.py
from django.urls import path
from .views import (cart_view, add_cart, reduce_quantity_view, delete_cart_item_view, checkout_view)

app_name = 'carts'
urlpatterns = [
    path('', cart_view, name='cart-view'),
    path('add_cart/<int:product_id>/', add_cart, name='add-cart'),
    path(
        'reduce_quantity_view/<int:product_id>/<int:cart_item_id>/', reduce_quantity_view, name='reduce-quantity-view'
    ),
    path(
        'delete_cart_item_view/<int:product_id>/<int:cart_item_id>/', delete_cart_item_view,
        name='delete-cart-item-view'
    ),
    path('checkout/', checkout_view, name='checkout-view')
]

accounts/forms.py
from django import forms
from .models import Account, UserProfile

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Enter password',
        'class':'form_control',
    }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Confirm password',
        'class':'form_control',
    }))
    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'email', 'phone_number', 'password']

    def __init__(self, *args, **kwargs):
        """ С помощью метода супер меняет действия init и меняет атрибуты полей формы """
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs["placeholder"] = "Enter First Name"
        self.fields['last_name'].widget.attrs["placeholder"] = "Enter Last Name"
        self.fields['email'].widget.attrs["placeholder"] = "Enter Email Address"
        self.fields['phone_number'].widget.attrs["placeholder"] = "Enter Phone Number"
        for field in self.fields:
            self.fields[field].widget.attrs["class"] = "form-control"



    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean() # https://docs.djangoproject.com/en/4.1/ref/forms/validation/
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError(
                'Password does not match!'
            )
        """The clean() method on a Field subclass is responsible for running to_python(), validate(), 
        and run_validators() in the correct order and propagating their errors. If, at any time, any of the 
        methods raise ValidationError, the validation stops and that error is raised. This method returns the 
        clean data, which is then inserted into the cleaned_data dictionary of the form.
        def clean проверяет на соответствие пароля и повторного пароля при регистрации и из-за использования 
        метода clean() возвращает ошибки, но нужно не забыть в шаблоне прописать теги для возвращения ошибок пользователю:
        """


class UserForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('first_name', 'last_name', 'phone_number')

    def __init__(self, *args, **kwargs):
        """ С помощью метода супер меняет действия init и меняет атрибуты полей формы """
        super(UserForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs["class"] = "form-control"

class UserProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(
        required=False, error_messages= {'invalid': ("Image files only")}, widget=forms.FileInput
    ) # убирает надпись с наименованием файла модели над формой
    class Meta:
        model = UserProfile
        fields = ('address', 'city', 'state', 'country', 'profile_picture')

    def __init__(self, *args, **kwargs):
        """ С помощью метода супер меняет действия init и меняет атрибуты полей формы """
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs["class"] = "form-control"

accounts/views.py
from django.shortcuts import render, redirect
from .forms import RegistrationForm, UserForm, UserProfileForm
from .models import Account, UserProfile
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required

# verification email
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.core.mail import EmailMessage
from django.contrib.auth.tokens import default_token_generator

import requests
from carts.models import Cart, CartItem
from carts.views import get_cart_id
from orders.models import Order, OrderProduct
from django.shortcuts import get_object_or_404
import logging, traceback

logger = logging.getLogger(__name__)


def register_view(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            phone_number = form.cleaned_data['phone_number']
            username = email.split('@')[0]

            user = Account.objects.create_user(
                first_name=first_name, last_name=last_name, username=username, email=email, password=password
            )
            user.phone_number = phone_number
            user.save()
            userprofile = UserProfile(
                user=user,
                address=None,
                profile_picture='/home/certo/projects/EcommersDjangoProject/Ecommerce/Ecommerce/static/images/avatars/avatar.png',
                city=None,
                state=None,
                country=None
            )
            userprofile.save()

            # USER ACTIVATION
            current_site = get_current_site(request)
            mail_subject = 'Please activate your account.'
            message = render_to_string('accounts/account_verification_message.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()
            return redirect('/accounts/login/?command=verification&email='+email) # for use if/else in login.html template

    else:
        form = RegistrationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/register.html', context)


def login_view(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        user = auth.authenticate(email=email, password=password) # https://docs.djangoproject.com/en/4.1/topics/auth/default/#django.contrib.auth.authenticate
        if user is not None:
            try:
                cart = Cart.objects.get(cart_id=get_cart_id(request))
                is_cart_item_exists = CartItem.objects.filter(cart=cart).exists()
                if is_cart_item_exists:
                    cart_item = CartItem.objects.filter(cart=cart)

                    # getting the product variations by cart id
                    product_variation = []
                    for item in cart_item:
                        variation = item.variations.all()
                        product_variation.append(list(variation))

                    # get the cart items from the user to access his product variations
                    cart_item = CartItem.objects.filter(user=user)
                    id_list = []
                    existing_variation_list = []
                    for item in cart_item:
                        existing_variation = item.variations.all()
                        existing_variation_list.append(list(existing_variation))
                        id_list.append(item.id)

                    for pr in product_variation:
                        if pr in existing_variation_list:
                            index = existing_variation_list.index(pr)
                            item_id = id[index]
                            item = CartItem.objects.get(id=item_id)
                            item.quantity += 1
                            item.user = user
                            item.save()
                        else:
                            cart_item = CartItem.objects.filter(cart=cart)
                            for item in cart_item:
                                item.user = user
                                item.save()

            except Exception:
                pass
            auth.login(request, user)
            messages.success(request, f'Welcome {user.first_name} to our store! We wish you a good time')
            url = request.META.get('HTTP_REFERER') # https://docs.djangoproject.com/en/4.1/ref/request-response/
            try:
                query = requests.utils.urlparse(url).query
                params = dict(x.split('=') for x in query.split('&'))
                if 'next' in params:
                    nextPage = params['next']
                return redirect(nextPage)
            except:
                return redirect('home')

        else:
            messages.error(request, 'invalid login or password')
            return redirect('accounts:login-view')

    return render(request, 'accounts/login.html')


@login_required(login_url='accounts:login-view')
def logout_view(request):
    auth.logout(request)
    messages.success(request, 'You are logged out')
    return redirect('accounts:login-view')


def activate_view(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode() # decode uidb64 get by url request and 'uid':urlsafe_base64_encode(force_bytes(user.pk)),
        user = Account._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None
        logger.exception('user activation error'), traceback

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Congraulations! Your account is activated.')
        return redirect('accounts:login-view')
    else:
        messages.error(request, 'Invalid activation link')

@login_required(login_url='accounts:login-view')
def dashboard_view(request):
    orders = Order.objects.filter(user_id=request.user.id, is_ordered=True)
    orders_count = orders.count()
    userprofile = UserProfile.objects.get(user__id=request.user.id)

    context = {
        'orders': orders,
        'orders_count': orders_count,
        'userprofile': userprofile,
    }
    return render(request, 'accounts/dashboard.html', context=context)

def forgot_password_view(request):
    if request.method == 'POST':
        email = request.POST['email']
        if Account.objects.filter(email=email).exists():
            user = Account.objects.get(email__exact=email)
            # reset password email
            current_site = get_current_site(request)
            mail_subject = 'Reset your password.'
            message = render_to_string('accounts/reset_password_message.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()

            messages.success(request, 'Password reset email has been sent to your email address.')
            return redirect('accounts:login-view')

        else:
            messages.error(request, 'Account does not exist. Please enter your account email.')
            return redirect('accounts:forgot-password-view')
    return render(request, 'accounts/forgot_password.html')

def password_validate_view(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(
            uidb64).decode()  # decode uidb64 get by url request and 'uid':urlsafe_base64_encode(force_bytes(user.pk)),
        user = Account._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None
        logger.exception('password validate error'), traceback

    if user is not None and default_token_generator.check_token(user, token):
        request.session['uid'] = uid
        messages.success(request, 'Please reset your password.')
        return redirect('accounts:reset-password-view')
    else:
        messages.error(request, 'This link has been expired!')
        return redirect('accounts:login-view')


def reset_password_view(request):
    if request.method == 'POST':
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            uid = request.session.get('uid')
            user = Account.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            messages.success(request, 'Password reset successful')
            return redirect('accounts:login-view')
        else:
            messages.error(request, 'Password do not match!')
            return redirect('accounts:reset-password-view')
    else:
        return render(request, 'accounts/resetPassword.html')

@login_required(login_url='accounts:login-view')
def my_orders_view(request):
    orders = Order.objects.filter(user_id=request.user.id, is_ordered=True).order_by('-created_at') # - in -created_at will give drscending result
    context = {
        'orders': orders,
    }

templates/accounts/account_verification_message.html
{% autoescape off %}

Hi {{ user.first_name }},

Please click on below link to confirm your registration.
http://{{domain}}{% url 'accounts:activate-view' uidb64=uid token=token %}

If you think it's not you, please ignore this email.

{% endautoescape %}

templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">

<div class="container">
    <div class="text-center">
        {% include 'includes/alerts.html' %}
    </div>
	<div class="row">
{#    sidebar #}
        {% include 'includes/dashboard_sidebar.html' %}

	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Change password</strong>
		</header>
		<div class="card-body">
            <div class="text-right">
                <img src="{{ userprofile.profile_picture.url }}" alt="Profile picture" height="100" width="100" style="border-radius:50%">
            </div>
			<div class="row">
                <div class="col-md-12">
                    <form action="{% url 'accounts:change-password-view' %}" method="POST">
                        {% csrf_token %}

                             <div class="form-group">
                                <label>Current password</label>
                                <input type="password" name="current_password" class="form-control" placeholder="Type current password" required>
                            </div>
                         <div class="form-group">
                                <label>New password</label>
                                <input type="password" name="new_password" class="form-control" placeholder="Type new password" required>
                            </div>
                         <div class="form-group">
                                <label>Confirm new password</label>
                                <input type="password" name="confirm_password" class="form-control" placeholder="Confirm password" required>
                            </div>


                        </div>
                        <input type="submit" class="btn btn-primary" value="Submit">
                    </form>
                </div>
			</div> <!-- row.// -->
		</div> <!-- card-body .// -->
		<div class="table-responsive">

		</div> <!-- table-responsive .end// -->
		</article> <!-- order-group.// -->
	</main>
</div> <!-- row.// -->
</div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">

<div class="container">
     <div class="text-center">
        {% include 'includes/alerts.html' %}
    </div>
	<div class="row">
        {% include 'includes/dashboard_sidebar.html' %}
{#	<aside class="col-md-3">#}
{#		<!--   SIDEBAR   -->#}
{#		<ul class="list-group">#}
{#			<a class="list-group-item active" href="#"> My order history </a>#}
{#			<a class="list-group-item" href="#"> Transactions </a>#}
{#			<a class="list-group-item" href="#"> Return and refunds </a>#}
{#			<a class="list-group-item" href="#">Settings </a>#}
{#			<a class="list-group-item" href="#"> My Selling Items </a>#}
{#			<a class="list-group-item" href="#"> Received orders </a>#}
{#		</ul>#}
{#		<br>#}
{#		<a class="btn btn-light btn-block" href="{% url 'accounts:logout-view' %}"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a>#}
{#		<!--   SIDEBAR .//END   -->#}
{#	</aside>#}
	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Logged in as: </strong>
			<span>{{ user.full_name }}</span>
		</header>
		<div class="card-body">
			<div class="row">
                <div class="col-md-7">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Total orders</h5>
                            <h4>{{ orders_count }}</h4>
                            <a href="{% url 'accounts:my-orders-view' %}">View orders</a>
                        </div>
                    </div>
                </div>
                 <div class="col-md-5">
                    <div class="card">
                        <div class="card-body text-center">
                           <img src="{{ userprofile.profile_picture.url }}" alt="User profile picture" width="50" height="50" style="border-radius: 50%">
                           <p>{{ user.email }}</p>
                            <p>{{ user.phone_number }}</p>
                        </div>
                    </div>
                </div>
			</div> <!-- row.// -->
		</div> <!-- card-body .// -->
		<div class="table-responsive">

		</div> <!-- table-responsive .end// -->
		</article> <!-- order-group.// -->
	</main>
</div> <!-- row.// -->
</div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">

<div class="container">
     <div class="text-center">
        {% include 'includes/alerts.html' %}
    </div>
	<div class="row">
{#    sidebar #}
        {% include 'includes/dashboard_sidebar.html' %}

	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Edit your profile</strong>
			<span>{{ user.full_name }}</span>
		</header>
		<div class="card-body">
            <div class="text-right">
                <img src="{{ userprofile.profile_picture.url }}" alt="Profile picture" height="100" width="100" style="border-radius:50%">
            </div>
			<div class="row">
                <div class="col-md-12">
                    <form action="{% url 'accounts:edit-profile-view' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label>First name</label>
                                {{ user_form.first_name }}
                            </div>
                            <div class="form-group col-md-6">
                                <label>Last name</label>
                                {{ user_form.last_name }}
                            </div>
                             <div class="form-group col-md-6">
                                <label>Phone number</label>
                                {{ user_form.phone_number }}
                            </div>
                            <div class="form-group col-md-6">
                                <label>Profile picture</label>
                                {{ profile_form.profile_picture }}
                            </div>
                             <div class="form-group col-md-12">
                                <label>Address</label>
                                {{ profile_form.address }}
                            </div>
                             <div class="form-group col-md-4">
                                <label>City</label>
                               {{ profile_form.city }}
                            </div> <div class="form-group col-md-4">
                                <label>State</label>
                                {{ profile_form.state }}
                            </div>
                             <div class="form-group col-md-4">
                                <label>Country</label>
                                {{ profile_form.country }}
                            </div>
                        </div>
                        <input type="submit" class="btn btn-primary" value="Save changes">
                    </form>
                </div>
			</div> <!-- row.// -->
		</div> <!-- card-body .// -->
		<div class="table-responsive">

		</div> <!-- table-responsive .end// -->
		</article> <!-- order-group.// -->
	</main>
</div> <!-- row.// -->
</div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/forgot_password.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

<!-- ============================ COMPONENT LOGIN   ================================= -->

    <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
      <div class="card-body">
      <h4 class="card-title mb-4">Forgot password</h4>
           {% include 'includes/alerts.html' %}
      <form action="{% url 'accounts:forgot-password-view' %}" method="POST">
          {% csrf_token %}
          <div class="form-group">
			 <input type="email" class="form-control" placeholder="Email Address" name="email">
          </div> <!-- form-group// -->
          <div class="form-group">
          	<a href="{% url 'accounts:login-view' %}" class="float-right">Got password? Login.</a>

          </div> <!-- form-group form-check .// -->
          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block">Submit</button>
          </div> <!-- form-group// -->
      </form>
      </div> <!-- card-body.// -->
    </div> <!-- card .// -->

     <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register-view' %}">Sign up</a></p>
     <br><br>
<!-- ============================ COMPONENT LOGIN  END.// ================================= -->

</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

<!-- ============================ COMPONENT LOGIN   ================================= -->
	{% if request.GET.command == 'verification' %}
    <div class="container mx-auto text-center alert alert-info" role="alert" style="max-width: 1024px; margin-top:100px;">
        Thank you for registering with us. We have sent you a verification email to you email address [{{ request.GET.email }}].
        Please verify it.
    <Br><Br>
    Already verified? <a href="{% url 'accounts:login-view' %}">Login</a>
    </div>
        {% else %}
    <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
      <div class="card-body">
      <h4 class="card-title mb-4">Sign in</h4>
           {% include 'includes/alerts.html' %}
      <form action="{% url 'accounts:login-view' %}" method="POST">
          {% csrf_token %}
          <div class="form-group">
			 <input type="email" class="form-control" placeholder="Email Address" name="email">
          </div> <!-- form-group// -->
          <div class="form-group">
			<input type="password" class="form-control" placeholder="Password" name="password">
          </div> <!-- form-group// -->
          <div class="form-group">
          	<a href="{% url 'accounts:forgot-password-view' %}" class="float-right">Forgot password?</a>

          </div> <!-- form-group form-check .// -->
          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block"> Login  </button>
          </div> <!-- form-group// -->
      </form>
      </div> <!-- card-body.// -->
    </div> <!-- card .// -->

     <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register-view' %}">Sign up</a></p>
     <br><br>
<!-- ============================ COMPONENT LOGIN  END.// ================================= -->
{% endif %}

</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/my_orders.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">

<div class="container">
	<div class="row">
{#    sidebar #}
        {% include 'includes/dashboard_sidebar.html' %}

	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Orders history </strong>
			<span>{{ user.full_name }}</span>
		</header>
		<div class="card-body">
			<div class="row">

            <table class="table">
              <thead>
                <tr>
                  <th scope="col">Order number</th>
                  <th scope="col">Order total price</th>
                  <th scope="col">Created at</th>
                    <th scope="col">Status</th>
                </tr>
              </thead>
              <tbody>
              {% for order in orders %}
                <tr>
                  <th scope="row"><a href="{% url 'accounts:order-detail-view' order.order_number %}">{{ order.order_number }}<br>(click for detail)</a></th>
                  <td>$ {{ order.order_total }}</td>
                  <td>{{ order.created_at }}</td>
                <td>{{ order.status }}</td>
                </tr>
              {% endfor %}
              </tbody>
            </table>

			</div> <!-- row.// -->
		</div> <!-- card-body .// -->
		<div class="table-responsive">

		</div> <!-- table-responsive .end// -->
		</article> <!-- order-group.// -->
	</main>
</div> <!-- row.// -->
</div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/resetPassword.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

<!-- ============================ COMPONENT LOGIN   ================================= -->

    <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
      <div class="card-body">
      <h4 class="card-title mb-4">Reset password</h4>
           {% include 'includes/alerts.html' %}
      <form action="{% url 'accounts:reset-password-view' %}" method="POST">
          {% csrf_token %}
          <div class="form-group">
			 <input type="password" class="form-control" placeholder="Create password" name="password">
          </div> <!-- form-group// -->
           <div class="form-group">
			 <input type="password" class="form-control" placeholder="Confirm password" name="confirm_password">
          </div> <!-- form-group// -->
          <div class="form-group">

          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block">Reset</button>
          </div> <!-- form-group// -->
      </form>
      </div> <!-- card-body.// -->
    </div> <!-- card .// -->

     <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register-view' %}">Sign up</a></p>
     <br><br>
<!-- ============================ COMPONENT LOGIN  END.// ================================= -->

</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/reset_password_message.html
{% autoescape off %}

Hi {{ user.first_name }},

As requested, please click on below link to reset your password.
http://{{domain}}{% url 'accounts:password-validate-view' uidb64=uid token=token %}

If you think it's not you, please ignore this email.

{% endautoescape %}