Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_view
from django.conf.urls.static import static
from django.conf import settings
from django.urls import re_path
from django.views.static import serve


urlpatterns = [
    path('adminlogin/', admin.site.urls),
    path('', home_view, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.register_view, name='register-view'),
    path('login/', views.login_view, name='login-view'),
    path('logout/', views.logout_view, name='logout-view'),
    path('activate/<uidb64>/<token>/', views.activate_view, name='activate-view'),
    path('dashboard/', views.dashboard_view, name='dashboard-view'),
    path('', views.dashboard_view, name='dashboard-view'),
    path('forgot_password/', views.forgot_password_view, name='forgot-password-view'),
    path('resetpassword/<uidb64>/<token>/', views.password_validate_view, name='password-validate-view'),
    path('reset_password/', views.reset_password_view, name='reset-password-view'),
    path('my_orders/', views.my_orders_view, name='my-orders-view'),
    path('edit_profile/', views.edit_profile_view, name='edit-profile-view'),
    path('change_password/', views.change_password_view, name='change-password-view'),
    path('order_detail/<int:order_id>/', views.order_detail_view, name='order-detail-view'),

    ]

carts/urls.py
from django.urls import path
from .views import (cart_view, add_cart, reduce_quantity_view, delete_cart_item_view, checkout_view)

app_name = 'carts'
urlpatterns = [
    path('', cart_view, name='cart-view'),
    path('add_cart/<int:product_id>/', add_cart, name='add-cart'),
    path(
        'reduce_quantity_view/<int:product_id>/<int:cart_item_id>/', reduce_quantity_view, name='reduce-quantity-view'
    ),
    path(
        'delete_cart_item_view/<int:product_id>/<int:cart_item_id>/', delete_cart_item_view,
        name='delete-cart-item-view'
    ),
    path('checkout/', checkout_view, name='checkout-view')
]

store/urls.py
from django.urls import path
from .views import store_view, product_detail_view, search_view, submit_review


app_name = 'store'
urlpatterns = [
    # {% url 'store:store-view' %}
    path('', store_view, name='store-view'),

    # store/models/Product/slug
    path('category/<slug:category_slug>/', store_view, name='products-by-category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', product_detail_view, name='product-detail'),
    path('search/', search_view, name='search-view'),
    path('submit_review/<int:product_id>/', submit_review, name='submit-review'),
]

templates/includes/alerts.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container" >
        <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
        {{ message }}
        </div>
        </div>
    {% endfor %}
{% endif %}

templates/includes/dashboard_sidebar.html
<aside class="col-md-3">
    <!--   SIDEBAR   -->
    <ul class="list-group">
        <a class="list-group-item {% if '/accounts/' == request.path %}active {% endif %}" href="{% url 'accounts:dashboard-view' %}"> Dashboard </a>
        <a class="list-group-item {% if '/my_orders/' in request.path %}active {% endif %}" href="{% url 'accounts:my-orders-view' %}"> My Orders </a>
        <a class="list-group-item {% if '/edit_profile/' in request.path %}active {% endif %}" href="{% url 'accounts:edit-profile-view' %}"> Edit Profile </a>
        <a class="list-group-item {% if '/change_password/' in request.path %}active {% endif %}" href="{% url 'accounts:change-password-view' %}">Change password</a>
    </ul>
    <br>
    <a class="btn btn-light btn-block" href="{% url 'accounts:logout-view' %}"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a>
    <!--   SIDEBAR .//END   -->
</aside>

templates/includes/footer.html
{% load static %}


<!-- ========================= FOOTER ========================= -->
<footer class="section-footer border-top mt-3">
	<div class="container mt-3">
		<section class="footer-bottom border-top row">
			<div class="col-md-2">
				<p class="text-muted"> &copy 2022 Company name </p>
			</div>
			<div class="col-md-8 text-md-center">
				<span  class="px-2">info@gmaill.com</span>
				<span  class="px-2">+879-332-9375</span>
				<span  class="px-2">Astana, Freedom street 543</span>
			</div>
			<div class="col-md-2 text-md-right text-muted">
				<i class="fab fa-lg fa-cc-visa"></i>
				<i class="fab fa-lg fa-cc-paypal"></i>
				<i class="fab fa-lg fa-cc-mastercard"></i>
			</div>
		</section>
	</div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->

<script>
    $(document).ready(function (){
        $('.thumb a').click(function (e){
            e.preventDefault();
            $('.mainImage img').attr('src', $(this).attr("href"));
        })
    })
</script>

</body>
</html>

templates/includes/navbar.html
{% load static %}

<header class="section-header mt-4 mb-3">

<nav class="navbar navbar-expand-md navbar-light bg-white border-bottom border-top">
    <div class="container mx-auto py-2">
        <a href="{% url 'home' %}" class="brand-wrap">
			<img class="logo" src="{% static './images/logo.png' %}">
		</a> <!-- brand-wrap.// -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto ">
      <li class="nav-item active">

        <div class="d-none d-lg-block col-lg">
		<div class="category-wrap dropdown d-inline-block float-right">
			<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
				<i class="fa fa-bars"></i> All category
			</button>
			<div class="dropdown-menu">
                {% for category in category_links %}
				    <a class="dropdown-item" href="{{ category.get_url }}">{{ category.category_name }}</a>
                {% endfor %}
			</div>
		</div>  <!-- category-wrap.// -->
	</div> <!-- col.// -->

      </li>
      <li class="nav-item">
          <div class="col-sm-12 col mt-2 my-md-0">
              <a href="{% url 'store:store-view' %}" class="btn btn-outline-primary d-block">Store</a>
          </div>

      </li>

     <li class="nav-item">

        <div class="col-lg col-lg-auto col-sm-12 col mt-2 my-md-0">
		<form action="{% url 'store:search-view' %}" class="search" method="GET">
			<div class="input-group w-100">
			    <input type="text" class="form-control" style="width:60%;" placeholder="Search" name="keyword">

			    <div class="input-group-append">
			      <button class="btn btn-primary" type="submit">
			        <i class="fa fa-search"></i>
			      </button>
			    </div>
		    </div>
		</form> <!-- search-wrap .end// -->
	</div> <!-- col.// -->

      </li>

    </ul>

  <div class="col-lg-4 col-sm-12 col-md-6 col order-2 order-lg-3">
				<div class="d-flex justify-content-center justify-content-md-end mt-3 my-md-0">
                {% if user.id is not None %}
					<div class="widget-header">
						<small class="title text-muted">Welcome {{ user.first_name }}!</small>
						<div>
							<a href="{% url 'accounts:dashboard-view' %}">Dashboard</a> <span class="dark-transp"> | </span>
							<a href="{% url 'accounts:logout-view' %}"> Logout </a>
						</div>
					</div>
                    {% else %}
                    <div class="widget-header">
						<small class="title text-muted">Welcome guest!</small>
						<div>
							<a href="{% url 'accounts:login-view' %}">Sign in</a> <span class="dark-transp"> | </span>
							<a href="{% url 'accounts:register-view' %}"> Register</a>
						</div>
					</div>
                    {% endif %}
					<a href="{% url 'carts:cart-view' %}" class="widget-header pl-3 ml-3">
						<div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
						<span class="badge badge-pill badge-danger notify">{{ cart_count }}</span>
					</a>
				</div> <!-- widgets-wrap.// -->
			</div> <!-- col.// -->
       </div>

</div>
</nav>
</header>

<!-- navbar //-->

templates/includes/oldnavbar.html
{% load static %}

<header class="section-header mb-3">
<nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
<div class="container">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTop4">
    <ul class="navbar-nav mr-auto">
    	<li class="nav-item dropdown">
		 	<a href="#" class="nav-link">   English </a>

		</li>
		<li class="nav-item dropdown">
			<a href="#" class="nav-link"> USD </a>
		</li>
    </ul>
    <ul class="navbar-nav">
		<li><a href="#" class="nav-link"> <i class="fa fa-envelope"></i> Email </a></li>
		<li><a href="#" class="nav-link"> <i class="fa fa-phone"></i> Call us </a></li>
	</ul> <!-- list-inline //  -->
  </div> <!-- navbar-collapse .// -->
</div> <!-- container //  -->
</nav>

<section class="header-main border-bottom">
	<div class="container">
<div class="row align-items-center">
	<div class="col-lg-2 col-md-3 col-6">
		<a href="{% url 'home' %}" class="brand-wrap">
			<img class="logo" src="{% static './images/logo.png' %}">
		</a> <!-- brand-wrap.// -->
	</div>
	<div class="col-lg col-sm col-md col-6 flex-grow-0">
		<div class="category-wrap dropdown d-inline-block float-right">
			<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
				<i class="fa fa-bars"></i> All category
			</button>
			<div class="dropdown-menu">
                {% for category in category_links %}
				    <a class="dropdown-item" href="{{ category.get_url }}">{{ category.category_name }}</a>
                {% endfor %}
			</div>
		</div>  <!-- category-wrap.// -->
	</div> <!-- col.// -->
	<a href="{% url 'store:store-view' %}" class="btn btn-outline-primary">Store</a>
	<div class="col-lg  col-md-6 col-sm-12 col">
		<form action="{% url 'store:search-view' %}" class="search" method="GET">
			<div class="input-group w-100">
			    <input type="text" class="form-control" style="width:60%;" placeholder="Search" name="keyword">

			    <div class="input-group-append">
			      <button class="btn btn-primary" type="submit">
			        <i class="fa fa-search"></i>
			      </button>
			    </div>
		    </div>
		</form> <!-- search-wrap .end// -->
	</div> <!-- col.// -->
	<div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
				<div class="d-flex justify-content-end mb-3 mb-lg-0">
                {% if user.id is not None %}
					<div class="widget-header">
						<small class="title text-muted">Welcome {{ user.first_name }}!</small>
						<div>
							<a href="{% url 'accounts:dashboard-view' %}">Dashboard</a> <span class="dark-transp"> | </span>
							<a href="{% url 'accounts:logout-view' %}"> Logout </a>
						</div>
					</div>
                    {% else %}
                    <div class="widget-header">
						<small class="title text-muted">Welcome guest!</small>
						<div>
							<a href="{% url 'accounts:login-view' %}">Sign in</a> <span class="dark-transp"> | </span>
							<a href="{% url 'accounts:register-view' %}"> Register</a>
						</div>
					</div>
                    {% endif %}
					<a href="{% url 'carts:cart-view' %}" class="widget-header pl-3 ml-3">
						<div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
						<span class="badge badge-pill badge-danger notify">{{ cart_count }}</span>
					</a>
				</div> <!-- widgets-wrap.// -->
			</div> <!-- col.// -->
</div> <!-- row.// -->
	</div> <!-- container.// -->
</section> <!-- header-main .// -->




</header> <!-- section-header.// -->