Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_view
from django.conf.urls.static import static
from django.conf import settings
from django.urls import re_path
from django.views.static import serve


urlpatterns = [
    path('adminlogin/', admin.site.urls),
    path('', home_view, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.register_view, name='register-view'),
    path('login/', views.login_view, name='login-view'),
    path('logout/', views.logout_view, name='logout-view'),
    path('activate/<uidb64>/<token>/', views.activate_view, name='activate-view'),
    path('dashboard/', views.dashboard_view, name='dashboard-view'),
    path('', views.dashboard_view, name='dashboard-view'),
    path('forgot_password/', views.forgot_password_view, name='forgot-password-view'),
    path('resetpassword/<uidb64>/<token>/', views.password_validate_view, name='password-validate-view'),
    path('reset_password/', views.reset_password_view, name='reset-password-view'),
    path('my_orders/', views.my_orders_view, name='my-orders-view'),
    path('edit_profile/', views.edit_profile_view, name='edit-profile-view'),
    path('change_password/', views.change_password_view, name='change-password-view'),
    path('order_detail/<int:order_id>/', views.order_detail_view, name='order-detail-view'),

    ]

carts/urls.py
from django.urls import path
from .views import (cart_view, add_cart, reduce_quantity_view, delete_cart_item_view, checkout_view)

app_name = 'carts'
urlpatterns = [
    path('', cart_view, name='cart-view'),
    path('add_cart/<int:product_id>/', add_cart, name='add-cart'),
    path(
        'reduce_quantity_view/<int:product_id>/<int:cart_item_id>/', reduce_quantity_view, name='reduce-quantity-view'
    ),
    path(
        'delete_cart_item_view/<int:product_id>/<int:cart_item_id>/', delete_cart_item_view,
        name='delete-cart-item-view'
    ),
    path('checkout/', checkout_view, name='checkout-view')
]

orders/urls.py
from django.urls import path
from .views import place_order_view, payments_view, order_complete_view

app_name = 'orders'
urlpatterns = [
    path('place_order/', place_order_view, name='place-order-view'),
    path('payments/', payments_view, name='payments-view'),
    path('order_complete/', order_complete_view, name='order-complete-view'),
]

store/urls.py
from django.urls import path
from .views import store_view, product_detail_view, search_view, submit_review


app_name = 'store'
urlpatterns = [
    # {% url 'store:store-view' %}
    path('', store_view, name='store-view'),

    # store/models/Product/slug
    path('category/<slug:category_slug>/', store_view, name='products-by-category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', product_detail_view, name='product-detail'),
    path('search/', search_view, name='search-view'),
    path('submit_review/<int:product_id>/', submit_review, name='submit-review'),
]

carts/models.py
from django.db import models
from store.models import Product, Variation
from accounts.models import Account


# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=256, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __unicode__(self):
        return self.product

store/models.py
from django.db import models
from category.models import Category
from django.shortcuts import reverse
from accounts.models import Account
from django.db.models import Avg, Count
from django.core.validators import MaxLengthValidator


# Create your models here.
class Product(models.Model):
    product_name = models.CharField(max_length=256, unique=True)
    slug = models.SlugField(max_length=256, unique=True, allow_unicode=True)
    description = models.TextField(max_length=512, blank=True, validators=[MaxLengthValidator(512, message='Maximum value exceeded')])
    price = models.IntegerField()
    images = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    popularity = models.IntegerField(default=0)
    # article
    # size
    # color

    def get_url(self):
        """Дает url на store_view из app store"""
        return reverse('store:product-detail', args=[self.category.slug, self.slug])


    def __str__(self):
        return self.product_name

    def average_rating(self):
        """Returns the average rating value"""
        # Avg - одна из списка ['Aggregate', 'Avg', 'Count', 'Max', 'Min', 'StdDev', 'Sum', 'Variance',]
        # функций работающих с полями баз данных.
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg

    def count_reviews(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count

class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)


variation_category_choice = (
    ('color', 'color'),
    ('size', 'size')
)


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=128, choices=variation_category_choice)
    variation_value = models.CharField(max_length=128)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=128, blank=True,)
    review = models.TextField(max_length=512, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=24, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject


class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/products', max_length=264)

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'

store/forms.py
from django import forms
from .models import ReviewRating


class ReviewRatingForm(forms.ModelForm):
    class Meta:

        model = ReviewRating
        fields = ['subject', 'review', 'rating']

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from store.models import Product, Variation
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
import logging, traceback

logger = logging.getLogger(__name__)


# Create your views here.
def get_cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    url = request.META.get('HTTP_REFERER')
    current_user = request.user
    product = Product.objects.get(id=product_id)  # get the product
    # if user authenticated
    if current_user.is_authenticated:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(
                        product=product, variation_category__iexact=key, variation_value__iexact=value
                    )  # __iexact - точное совпадение без учета регистра
                    product_variation.append(variation)
                except:
                    pass
        is_cart_item_exist = CartItem.objects.filter(product=product, user=current_user).exists()
        if is_cart_item_exist:
            cart_item = CartItem.objects.filter(product=product, user=current_user)
            # existing_variations --> Database
            # current variations --> product_variations
            # item_id --> Database
            id_list = []
            existing_variation_list = []
            for item in cart_item:
                existing_variation = item.variations.all()
                existing_variation_list.append(list(existing_variation))
                id_list.append(item.id)

            if product_variation in existing_variation_list:
                # increase the cart item quantity
                index = existing_variation_list.index(product_variation)  # list method index
                item_id = id_list[index]
                item = CartItem.objects.get(product=product, id=item_id)
                if item.quantity < product.stock:
                    item.quantity += 1
                    item.save()
                else:
                    pass
            else:
                # create a new cart item
                item = CartItem.objects.create(product=product, user=current_user, quantity=1)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                user=current_user,
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()

        return redirect(url)
    # if user is not authenticated
    else:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(
                        product=product, variation_category__iexact=key, variation_value__iexact=value
                    ) # __iexact - точное совпадение без учета регистра
                    product_variation.append(variation)
                except:
                    pass

        try:
            cart = Cart.objects.get(cart_id=get_cart_id(request))  # получить корзину используемую в текущей сессии
        except Cart.DoesNotExist:
            cart = Cart.objects.create(cart_id=get_cart_id(request))
            cart.save()

        is_cart_item_exist = CartItem.objects.filter(product=product, cart=cart).exists()
        if is_cart_item_exist:
            cart_item = CartItem.objects.filter(product=product, cart=cart)
            # existing_variations --> Database
            # current variations --> product_variations
            # item_id --> Database
            id_list = []
            existing_variation_list = []
            for item in cart_item:
                existing_variation = item.variations.all()
                existing_variation_list.append(list(existing_variation))
                id_list.append(item.id)

            if product_variation in existing_variation_list:
                # increase the cart item quantity
                index = existing_variation_list.index(product_variation) # list method index
                item_id = id_list[index]
                item = CartItem.objects.get(product=product, id=item_id)
                if item.quantity < product.stock:
                    item.quantity += 1
                    item.save()
                else:
                    pass
            else:
                # create a new cart item
                item = CartItem.objects.create(product=product, cart=cart, quantity=1)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                cart=cart,
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()

        return redirect(url)


def reduce_quantity_view(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)  # get the product
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=get_cart_id(request))  # get cart using in current session
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except Exception:
        logger.exception('reduce_quantity_view error'), traceback

    return redirect('carts:cart-view')


def delete_cart_item_view(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=get_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    try:
        cart_item.delete()
    except:
        pass
    return redirect('carts:cart-view')

# it is required to fix the problem with the fact that during authentication items from the cart are not transferred to the user's cart
def cart_view(request, total=0, quantity=0, cart_items=None):
    total_plus_tax = 0
    tax = 0
    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=get_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (4 * total)/100
        total_plus_tax = total + tax
    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'total_plus_tax':total_plus_tax,
    }
    return render(request, 'store/cart.html', context=context)

# it is required to fix the problem with the fact that during authentication items from the cart are not transferred to the user's cart
@login_required(login_url='accounts:login-view')
def checkout_view(request, total=0, quantity=0, cart_items=None):
    total_plus_tax = 0
    tax = 0
    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=get_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (4 * total)/100
        total_plus_tax = total + tax
    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'total_plus_tax':total_plus_tax,
    }
    return render(request, 'store/checkout.html', context)

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="section-content padding-y bg">
<div class="container">
<!-- ============================ COMPONENT 1 ================================= -->
{% if not cart_items %}
    <h2 class="text-center">Your shopping cart is empty</h2>
    <div class="text-center">
    <a href="{% url 'store:store-view' %}" class="btn btn-primary">Continue shopping</a>
    </Div>
{% else %}


<div class="row"> <!-- row -->
	<aside class="col-lg-9">
<div class="card">
<table class="table table-borderless table-shopping-cart">
<thead class="text-muted">
<tr class="small text-uppercase">
  <th scope="col">Product</th>
  <th scope="col" width="120">Quantity</th>
  <th scope="col" width="120">Price</th>
  <th scope="col" class="text-right" width="200"> </th>
</tr>
</thead>
<tbody>
{% for cart_item in cart_items %}
<tr>
	<td>
		<figure class="itemside align-items-center">
			<div class="aside"><img src="{{ cart_item.product.images.url }}" class="img-sm"></div>
			<figcaption class="info">
				<a href="#" class="title text-dark">{{ cart_item.product.product_name }}</a>
				<p class="text-muted small">
                    {% if cart_item.variations.all %}
                         {% for item in cart_item.variations.all %}
                             {{ item.variation_category | capfirst }} : {{ item.variation_value | capfirst }} <br>
                         {% endfor %}
                    {% endif %}
                </p>
			</figcaption>
		</figure>
	</td>
	<td>
		<!-- col.// -->
					<div class="col">
						<div class="input-group input-spinner">
							<div class="input-group-prepend">
							<a href="{% url 'carts:reduce-quantity-view' cart_item.product.id cart_item.id %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
							</div>
							<input type="text" class="form-control"  value="{{ cart_item.quantity }}">
							<div class="input-group-append">
                            <form action="{% url 'carts:add-cart' cart_item.product.id %}" method="POST">
                                {% csrf_token %}
                                {% for item in cart_item.variations.all %}
                                    <input type="hidden" name="{{ item.variation_category | lower }}" value="{{ item.variation_value |capfirst }}">
                                {% endfor %}
							<button class="btn btn-light" type="submit" id="button-minus"> <i class="fa fa-plus"></i> </button>
							</form>
                            </div>
						</div> <!-- input-group.// -->
					</div> <!-- col.// -->
	</td>
	<td>
		<div class="price-wrap">
			<var class="price">${{ cart_item.sub_total }}</var>
			<small class="text-muted">{{ cart_item.product.price }} each </small>
		</div> <!-- price-wrap .// -->
	</td>
	<td class="text-right">
	<a href="{% url 'carts:delete-cart-item-view' cart_item.product.id cart_item.id %}" onclick="return confirm("Are you sure you want to delete this item?")" class="btn btn-danger d-none d-sm-block"> Remove</a>
	</td>
</tr>
{% endfor %}
</tbody>
</table>
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-3">

		<div class="card">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Total price:</dt>
			  <dd class="text-right">${{ total }}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Tax:</dt>
			  <dd class="text-right"> ${{ tax }}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Total:</dt>
			  <dd class="text-right text-dark b"><strong>${{ total_plus_tax }}</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src="{% static './images/misc/payments.png' %}" height="26">
			</p>
			<a href="{% url 'carts:checkout-view' %}" class="btn btn-primary btn-block"> Checkout </a>
			<a href="{% url 'store:store-view' %}" class="btn btn-light btn-block">Continue Shopping</a>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside> <!-- col.// -->


</div> <!-- row.// -->
{% endif %}
<!-- ============================ COMPONENT 1 END .// ================================= -->

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/store/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}


<!-- ============================ COMPONENT 1 ================================= -->
{% include 'includes/alerts.html' %}
<div class="card">
	<div class="row no-gutters">
		<aside class="col-md-6">
<article class="gallery-wrap">
	<div class="img-big-wrap mainImage">
	   <center><img src="{{ single_product.images.url }}"></center>
	</div> <!-- img-big-wrap.// -->

</article> <!-- gallery-wrap .end// -->
            <ul class="thumb">
                <li>
                <a href="{{ single_product.images.url }}" target="mainImage"><img src="{{ single_product.images.url }}" alt="Product Image"></a>
                    {% for i in product_gallery %}
                    <a href="{{ i.image.url }}" target="mainImage"><img src="{{ i.image.url }}" alt="Product Image"></a>
                    {% endfor %}
                </li>
            </ul>
		</aside>
		<main class="col-md-6 border-left">

<form action="{% url 'carts:add-cart' single_product.id %}" method="POST">
    {% csrf_token %}
    <article class="content-body">

    <h2 class="title">{{ single_product.product_name }}</h2>
     <span>
         <i class="fa fa-star{% if single_product.average_rating < 0.5 %}-o {% elif single_product.average_rating >= 0.5 and single_product.average_rating < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
         <i class="fa fa-star{% if single_product.average_rating < 1.5 %}-o {% elif single_product.average_rating >= 1.5 and single_product.average_rating < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
         <i class="fa fa-star{% if single_product.average_rating < 2.5 %}-o {% elif single_product.average_rating >= 2.5 and single_product.average_rating < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
         <i class="fa fa-star{% if single_product.average_rating < 3.5 %}-o {% elif single_product.average_rating >= 3.5 and single_product.average_rating < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
         <i class="fa fa-star{% if single_product.average_rating < 4.5 %}-o {% elif single_product.average_rating >= 4.5 and single_product.average_rating < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
     </span>
    <span>({{ single_product.count_reviews }} reviews)</span>
    <div class="mb-3">
        <var class="price h4">$ {{ single_product.price }}</var>
    </div>
    <p>{{ single_product.description }}</p>
    <hr>
        <div class="row">
            <div class="item-option-select">
                <h6>Choose Color</h6>
                    <select name="color"  class="form-control" required>
                        <option value="" disabled selected>Choose Color</option>
                        {% for i in single_product.variation_set.colors %} <!--_set.all  https://stackoverflow.com/questions/25386119/whats-the-difference-between-a-onetoone-manytomany-and-a-foreignkey-field-in-d-->
                        <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst}}</option>
                        {% endfor %}
                    </select>
            </div>
        </div> <!-- row.// -->
        <div class="row">
            <div class="item-option-select">
                <h6>Select Size</h6>
                    <select name="size" class="form-control">
                        <option value="" disabled selected>Select Size</option>
                        {% for i in single_product.variation_set.sizes %} <!--_set.all  https://stackoverflow.com/questions/25386119/whats-the-difference-between-a-onetoone-manytomany-and-a-foreignkey-field-in-d-->
                        <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst}}</option>
                        {% endfor %}
                    </select>
            </div>
        </div> <!-- row.// -->
        <hr>
        {% if single_product.stock <= 0 %}
            <h5 class="text-danger">Out of stock</h5>
            {% else %}
            {% if in_cart %}
                <button class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </button>
                <a href="{% url 'store:store-view' %}" class="btn  btn-primary"> <span class="text">Continue shopping</span></a>
                 <a href="{% url 'carts:cart-view' %}" class="btn  btn-primary"> <span class="text">Cart</span></a>
                {% else %}
                <button class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </button>
            {% endif %}
        {% endif %}
    </article> <!-- product-info-aside .// -->
</form>
		</main> <!-- col.// -->
	</div> <!-- row.// -->
</div> <!-- card.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

<br>

<div class="row">
			<div class="col-md-9">

	<header class="section-heading">
		<h3>Customer Reviews </h3>

	</header>

        <form action="{% url 'store:submit-review' single_product.id %}" method="POST">
            {% csrf_token %}
            <h5>Write your review</h5>
            <div class="form-group">
                {# rating stars #}
                <label>How do you rate this product?</label>
                <br>
                <div class="rate">
                    <!-- https://www.w3schools.com/icons/fontawesome_icons_intro.asp //-->
                    <input type="radio" name="rating" id="rating10" value="5" required><label for="rating10" title="5"></label>
                    <input type="radio" name="rating" id="rating9" value="4.5" required><label for="rating9" title="4.5" class="half"></label>
                    <input type="radio" name="rating" id="rating8" value="4" required><label for="rating8" title="4"></label>
                    <input type="radio" name="rating" id="rating7" value="3.5" required><label for="rating7" title="3.5" class="half"></label>
                    <input type="radio" name="rating" id="rating6" value="3" required><label for="rating6" title="3"></label>
                    <input type="radio" name="rating" id="rating5" value="2.5" required><label for="rating5" title="2.5" class="half"></label>
                    <input type="radio" name="rating" id="rating4" value="2" required><label for="rating4" title="2"></label>
                    <input type="radio" name="rating" id="rating3" value="1.5" required><label for="rating3" title="1.5" class="half"></label>
                    <input type="radio" name="rating" id="rating2" value="1" required><label for="rating2" title="1"></label>
                    <input type="radio" name="rating" id="rating1" value="1" required><label for="rating1" title="0.5" class="half"></label>
                </div>
                <br>
                Review Title:
                <input type="text" class="form-control" name="subject">
                <br>
                Review:
                <textarea name="review" rows="4" class="form-control"></textarea>
                <br>
                {% if user.is_authenticated %}
                    {% if orderproduct %}
                <input type="submit" class="btn btn-primary" value="Submit review">
                        {% else %}
                        <p>You can leave a review only for the purchased product.</p>
                        {% endif %}
                {% else %}
                    <p>You must be logged in to post a review.<span><a href="{% url 'accounts:login-view' %}">Login now</a> </span></p>
                {% endif %}
                <br>
            </div>
        </form>
<br>
{% for review in reviews %}
	<article class="box mb-3">
		<div class="icontext w-100">
			<img src="{{ user_profile.profile_picture.url }}" class="img-xs icon rounded-circle">
			<div class="text">
				<span class="date text-muted float-md-right">{{ review.updated_at }}</span>
                <div>
                    <span>
                    <i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
                    </span>
                </div>
                <h6 class="mb-1">{{ review.user.full_name}} </h6>
			</div>
		</div> <!-- icontext.// -->
		<div class="mt-3">
            <h6>{{ review.subject }}</h6>
			<p>{{ review.review }}</p>
		</div>
	</article>
{% endfor %}



	</div> <!-- col.// -->
</div> <!-- row.// -->


</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->


{% endblock %}